### PR TITLE
Add phantomjs.

### LINKED ISSUE #3: Add phantomjs.
As this is our base container for clojure and clojurescript projects, we need phantomjs to run clojurescript tests. This will also solve most of our problems with problematic phantomjs downloads as once this container is built, it will rarely be re-built.

### PR DESCRIPTION
**Pull request by tvaughan**
Fixes #3 .

### CODE REVIEW

**Comment by tvaughan** [comment]
Proof!

```
$ ./phantomjs 
Starting addphantomjs_lein-volume_1
phantomjs> console.log("Hello, World!");
Hello, World!
undefined
```

**Comment by stevebrewer** [comment]
That's easy :) Was lein downloading it before?

**Comment by rebeccamadsen** [comment]
+1

**Comment by tvaughan** [comment]
> That's easy :) Was lein downloading it before?

We did it in each clojurescript project separately. https://github.com/lynxtp/villarrica-frontend/blob/add-project-template/Dockerfile. We had to repeat the download each time we built a new version. Totally unnecessary as it's a static dependency.

**Comment by tvaughan** [comment]
Each clojurescript (and clojure) project uses this container as their base. So they'll all pick this up automatically as soon as it's built on the Docker Hub.

**Comment by stevebrewer** [comment]
Makes sense 👍

**Pull request merged**
